// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekkggkqqietwmlefcrir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVra2dna3FxaWV0d21sZWZjcmlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NTcyMzMsImV4cCI6MjA2OTAzMzIzM30.ZxMQw8HqbprImSDGVnPwlDw7DE4oC-d11WPUWrGBQQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});